export const MY_RESUME_DATA = [
  {
    title: 'Quem sou eu?',
    description:
      'Meu nome é Daniel Benício, sou natural de Barueri-SP e minha história com os computadores começou bem cedo, quando criança adorava jogar games: Minecraft, Grand Chase, CS 1.6, etc. ./ Quando estava com meus 14 anos comecei a ligar meu lado criativo e conhecer a programação, comecei com HTML, CSS fazendo sites bem feios (haha), mas com o tempo fui me especializando e treinando, hoje me considero muito bom no que faço. Adoro fazer sites com React, interfaces bonitas (frufruzadas como meu professor costumava dizer), aplicativos mobiles com React Native e APIs NodeJS. ./ Minhas principais ferramentas de trabalho são: NextJS, NodeJS, TypeScript, CSS-in-JS(TailwindCSS, Stitches, Styled Components), também tenho proficiência em várias ferramentas da AWS como Dynamodb, Lambdas, S3, Amplify, etc. ./ Atualmente estou cursando Engenharia da computação na faculdade São Judas Tadeu localizada na Avenida Paulista. ./ Agora que contei um pouco da minha história com a programação, aproveito o espaço para falar um pouco sobre mim. No meu tempo vago adoro ler sobre mitologias de todas as culturas, jogar um Valorant bem jogado(sou gold, mas pelo menos tento). Minha série preferida é Game of Thrones, mas adorei The Last Of Us, então como o final de GOT foi decepcionante estou inclinado a trocar de série preferida. Também adoro esportes como futebol, vôlei, musculação, corrida, tênis, etc.',
  },
  {
    title: 'Minhas experiências',
    description:
      'LAB2DEV - Desenvolvedor Full-stack - (Abril de 2022 - Hoje). .\\ Fui responsável pelo desenvolvimento e manutenção de soluções Full-stack. ./ Ferramentas: ReactJS, Typescript, Node, Express, AWS. ./ * Desenvolvimento de soluções front-end com ReactJS, Typescript, Styled Components, Radix, etc.; .\\ * Desenvolvimento de soluções back-end com Node, Express e Typescript; .\\ * Utilizando conceitos de arquitetura e boas práticas como SOLID, Clean Code, etc.; .\\ * Utilizando ferramentas da AWS como Lambda, S3, Dynamo e SQS. .\\ * Monitoramento de aplicações de grande escala na AWS utilizando CloudWatch. ./ ./  LAB2DEV - Desenvolvedor Front-end - 3 meses (Fevereiro de 2022 - Abril de 2022) .\\ Fui responsável pelo desenvolvimento e manutenção de soluções Front-end. Também atuei como UX/UI dentro de empresas como Swift, Whirpool E Hospital Albert Einstein. ./ Ferramentas: NextJS, ReactJS, Redux, Typescript.* Desenvolvimento Web com ReactJS e Typescript; ./ * Páginas estilizadas com CSS-in-JS: temas e animações incluídos; .\\ * Implementação de gerenciamento de estado global com Redux e Context API. Fui responsável pelo desenvolvimento e manutenção de soluções Front-end para grandes empresas. ./ ./  IT POWER SOFTWARE - Estágio - 6 meses(Janeiro de 2021 - Junho de 2021) .\\ Atuando com automação e desenvolvimento web, trabalhei criando e mantendo não só o back-end, mas também o front-end de diversos clientes. ./ Ferramentas: ColdFusion, JavaScript, Python, Selenium, Tesseract, OpenCV. ./ * Desenvolvimento Web com ColdFusion, Bootstrap e JavaScript; .\\ * Desenvolvimento de RPA para automatização de tarefas repetitivas, desde tarefas curtas como preenchimento de formulários até download de documentos e sua validação com Python, PyAutoGUI e Selenium; .\\ * Desenvolvimento de OCR para reconhecimento de documentos e validação com Python, Tesseract e OpenCV. ./ ./ Formações Acadêmicas: ./ Bacharel em Engenharia de Computação - Universidade São Judas Tadeu. .\\ Curso Técnico - Tecnologia da Informação - Instituto Técnico de Barueri.',
  },
  {
    title: 'Projetos',
    description:
      'Você pode ver meus projetos acessando meu Github: .\\ https://github.com/danielbenicio ./ Você pode entrar em contato comigo via: .\\ Email: danielbenicio123@gmail.com ./ Minhas redes sociais: .\\ Linkedin: .\\ https://www.linkedin.com/in/danielbenicio/ .\\ Instagram: .\\ https://www.instagram.com/_benicioz/',
  },
]
